"""Initial migration with name field

Revision ID: c541edc48932
Revises: 
Create Date: 2025-08-26 15:51:18.092098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c541edc48932'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placeholders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placeholders_name'), 'placeholders', ['name'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_category'), 'profiles', ['category'], unique=False)
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('placeholder_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('placeholder_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placeholder_id'], ['placeholders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placeholder_values_name'), 'placeholder_values', ['name'], unique=False)
    op.create_table('profile_placeholder_settings',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('placeholder_id', sa.Uuid(), nullable=False),
    sa.Column('placeholder_value_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placeholder_id'], ['placeholders.id'], ),
    sa.ForeignKeyConstraint(['placeholder_value_id'], ['placeholder_values.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'placeholder_id')
    )
    op.create_table('user_placeholder_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('placeholder_id', sa.Uuid(), nullable=False),
    sa.Column('placeholder_value_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['placeholder_id'], ['placeholders.id'], ),
    sa.ForeignKeyConstraint(['placeholder_value_id'], ['placeholder_values.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'placeholder_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_placeholder_settings')
    op.drop_table('profile_placeholder_settings')
    op.drop_index(op.f('ix_placeholder_values_name'), table_name='placeholder_values')
    op.drop_table('placeholder_values')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_category'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_placeholders_name'), table_name='placeholders')
    op.drop_table('placeholders')
    # ### end Alembic commands ###
